package beans;
// Generated Dec 13, 2018 12:47:24 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

/**
 *ArticleBeane generated by hbm2java
 */

@ManagedBean()
@SessionScoped
public class ArticleBean  implements java.io.Serializable {

     private String articleName;
     private double articlePrice;
     private int articleStock;
     private Set wbCrStocks = new HashSet(0);
     private Set wbCrBilldetails = new HashSet(0);

    public ArticleBean() {
    }

	
    public ArticleBean(String articleName, double articlePrice, int articleStock) {
        this.articleName = articleName;
        this.articlePrice = articlePrice;
        this.articleStock = articleStock;
    }
    public ArticleBean(String articleName, double articlePrice, int articleStock, Set wbCrStocks, Set wbCrBilldetails) {
       this.articleName = articleName;
       this.articlePrice = articlePrice;
       this.articleStock = articleStock;
       this.wbCrStocks = wbCrStocks;
       this.wbCrBilldetails = wbCrBilldetails;
    }
    public void setArticleName(String articleName) {
        this.articleName = articleName;
    }

    public String getArticleName() {
        return articleName;
    }

    public double getArticlePrice() {
        return this.articlePrice;
    }
    
    public void setArticlePrice(double articlePrice) {
        this.articlePrice = articlePrice;
    }

    public int getArticleStock() {
        return articleStock;
    }

    public void setArticleStock(int articleStock) {
        this.articleStock = articleStock;
    }

    public Set getWbCrStocks() {
        return wbCrStocks;
    }

    public void setWbCrStocks(Set wbCrStocks) {
        this.wbCrStocks = wbCrStocks;
    }

    public Set getWbCrBilldetails() {
        return wbCrBilldetails;
    }
    
}


