package beans;
// Generated Dec 13, 2018 12:47:24 AM by Hibernate Tools 4.3.1


import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.persistence.Column;

/**
 * BilldetailBean generated by hbm2java
 */

@ManagedBean()
@SessionScoped
public class BilldetailBean  implements java.io.Serializable {

     private ArticleBean wbCrArticle;
     private BillBean wbCrBill;
     private int detailAmount;

    public BilldetailBean() {
    }

    public BilldetailBean(ArticleBean wbCrArticle, BillBean wbCrBill, int detailAmount) {
       this.wbCrArticle = wbCrArticle;
       this.wbCrBill = wbCrBill;
       this.detailAmount = detailAmount;
    }
    
    public BillBean getWbCrBill() {
        return this.wbCrBill;
    }
    
    public void setWbCrBill(BillBean wbCrBill) {
        this.wbCrBill = wbCrBill;
    }

    
    @Column(name="DETAIL_AMOUNT", nullable=false)
    public int getDetailAmount() {
        return this.detailAmount;
    }
    
    public void setDetailAmount(int detailAmount) {
        this.detailAmount = detailAmount;
    }

    public ArticleBean getWbCrArticle() {
        return wbCrArticle;
    }

    public void setWbCrArticle(ArticleBean wbCrArticle) {
        this.wbCrArticle = wbCrArticle;
    }
}


