package beans;
// Generated Dec 13, 2018 12:47:24 AM by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import model.WbCrCity;

/**
 * CityBean generated by hbm2java
 */
@ManagedBean()
@SessionScoped
public class CityBean implements java.io.Serializable
{

    private int cityId;
    private String cityName;
    private ArrayList<WbCrCity> cityList;
    private String filterString;
    private ArrayList<WbCrCity> filteredList;
    private Set wbCrBills = new HashSet(0);

    public CityBean()
    {
    }

    public CityBean(int cityId, String cityName)
    {
        this.cityId = cityId;
        this.cityName = cityName;
    }

    public CityBean(int cityId, String cityName, Set wbCrBills)
    {
        this.cityId = cityId;
        this.cityName = cityName;
        this.wbCrBills = wbCrBills;
    }

    public int getCityId()
    {
        return this.cityId;
    }

    public void setCityId(int cityId)
    {
        this.cityId = cityId;
    }

    public String getCityName()
    {
        return this.cityName;
    }

    public void setCityName(String cityName)
    {
        this.cityName = cityName;
    }

    public Set getWbCrBills()
    {
        return this.wbCrBills;
    }

    public void setWbCrBills(Set wbCrBills)
    {
        this.wbCrBills = wbCrBills;
    }

    public ArrayList<WbCrCity> getCityList()
    {
        cityList = controller.CityPersistance.getInstance().getAll();
        return cityList;
    }

    public String getFilterString()
    {
        return filterString;
    }

    public void setFilterString(String filterString)
    {
        this.filterString = filterString;
    }

    public ArrayList<WbCrCity> getFilteredList()
    {
        if(filteredList == null) filteredList = new ArrayList<>();
        return filteredList;
    }
    
    public void filter()
    {
        if (cityList != null && getFilteredList() != null && filterString != null)
        {
            if (cityList.size() >= 1)
            {
                getFilteredList().clear();
                cityList.forEach(x ->
                {
                    if (x.getCityName().toUpperCase().contains(filterString.toUpperCase()))
                    {
                        getFilteredList().add(x);
                    }
                });

            }
        }

    }
    
    
}
