package beans;
// Generated Dec 13, 2018 12:47:24 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ClientBean generated by hbm2java
 */
public class ClientBean  implements java.io.Serializable {

     private String clientDni;
     private String clientName;
     private String clientAddress;
     private Set wbCrBills = new HashSet(0);

    public ClientBean() {
    }

    public ClientBean(int clientId, String clientDni, String clientName) {
        this.clientDni = clientDni;
        this.clientName = clientName;
    }
    public ClientBean(int clientId, String clientDni, String clientName, String clientAddress, Set wbCrBills) {
       this.clientDni = clientDni;
       this.clientName = clientName;
       this.clientAddress = clientAddress;
       this.wbCrBills = wbCrBills;
    }

    public String getClientDni() {
        return this.clientDni;
    }
    
    public void setClientDni(String clientDni) {
        this.clientDni = clientDni;
    }

    public String getClientName() {
        return this.clientName;
    }
    
    public void setClientName(String clientName) {
        this.clientName = clientName;
    }

    public String getClientAddress() {
        return this.clientAddress;
    }
    
    public void setClientAddress(String clientAddress) {
        this.clientAddress = clientAddress;
    }

    public Set getWbCrBills() {
        return this.wbCrBills;
    }
    
    public void setWbCrBills(Set wbCrBills) {
        this.wbCrBills = wbCrBills;
    }

}


