package beans;
// Generated Dec 13, 2018 12:47:24 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * MovementBean generated by hbm2java
 */
public class MovementBean  implements java.io.Serializable {

     private String movementName;
     private String movementDirection;
     private Set wbCrStocks = new HashSet(0);

    public MovementBean() {
    }

	
    public MovementBean(String movementName, String movementDirection) {
        this.movementName = movementName;
        this.movementDirection = movementDirection;
    }
    public MovementBean(String movementName, String movementDirection, Set wbCrStocks) {
       this.movementName = movementName;
       this.movementDirection = movementDirection;
       this.wbCrStocks = wbCrStocks;
    }
    
    public String getMovementName() {
        return this.movementName;
    }
    
    public void setMovementName(String movementName) {
        this.movementName = movementName;
    }

    public String getMovementDirection() {
        return this.movementDirection;
    }
    
    public void setMovementDirection(String movementDirection) {
        this.movementDirection = movementDirection;
    }

    public Set getWbCrStocks() {
        return this.wbCrStocks;
    }
    
    public void setWbCrStocks(Set wbCrStocks) {
        this.wbCrStocks = wbCrStocks;
    }
}


