package beans;
// Generated Dec 13, 2018 12:47:24 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * StockBean generated by hbm2java
 */

public class StockBean  implements java.io.Serializable {

     private ArticleBean wbCrArticle;
     private MovementBean wbCrMovement;
     private Integer strockNumber;
     private Date stockDate;
     private Integer stock;

    public StockBean() {
    }

	
    public StockBean(ArticleBean wbCrArticle, MovementBean wbCrMovement) {
        this.wbCrArticle = wbCrArticle;
        this.wbCrMovement = wbCrMovement;
    }
    public StockBean(ArticleBean wbCrArticle, MovementBean wbCrMovement, Integer strockNumber, Date stockDate, Integer stock) {
       this.wbCrArticle = wbCrArticle;
       this.wbCrMovement = wbCrMovement;
       this.strockNumber = strockNumber;
       this.stockDate = stockDate;
       this.stock = stock;
    }

    public ArticleBean getWbCrArticle() {
        return this.wbCrArticle;
    }

    public void setWbCrArticle(ArticleBean wbCrArticle) {
        this.wbCrArticle = wbCrArticle;
    }
    
    public MovementBean getWbCrMovement() {
        return this.wbCrMovement;
    }
    
    public void setWbCrMovement(MovementBean wbCrMovement) {
        this.wbCrMovement = wbCrMovement;
    }

    
    public Integer getStrockNumber() {
        return this.strockNumber;
    }
    
    public void setStrockNumber(Integer strockNumber) {
        this.strockNumber = strockNumber;
    }
    
    public Date getStockDate() {
        return this.stockDate;
    }
    
    public void setStockDate(Date stockDate) {
        this.stockDate = stockDate;
    }

    public Integer getStock() {
        return this.stock;
    }
    
    public void setStock(Integer stock) {
        this.stock = stock;
    }

}


