package project.model;
// Generated Dec 12, 2018 11:08:37 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * WbCrArticle generated by hbm2java
 */
public class WbCrArticle  implements java.io.Serializable {


     private int articleId;
     private String articleName;
     private double articlePrice;
     private int articleStock;
     private Set wbCrStocks = new HashSet(0);
     private Set wbCrBilldetails = new HashSet(0);

    public WbCrArticle() {
    }

	
    public WbCrArticle(int articleId, String articleName, double articlePrice, int articleStock) {
        this.articleId = articleId;
        this.articleName = articleName;
        this.articlePrice = articlePrice;
        this.articleStock = articleStock;
    }
    public WbCrArticle(int articleId, String articleName, double articlePrice, int articleStock, Set wbCrStocks, Set wbCrBilldetails) {
       this.articleId = articleId;
       this.articleName = articleName;
       this.articlePrice = articlePrice;
       this.articleStock = articleStock;
       this.wbCrStocks = wbCrStocks;
       this.wbCrBilldetails = wbCrBilldetails;
    }
   
    public int getArticleId() {
        return this.articleId;
    }
    
    public void setArticleId(int articleId) {
        this.articleId = articleId;
    }
    public String getArticleName() {
        return this.articleName;
    }
    
    public void setArticleName(String articleName) {
        this.articleName = articleName;
    }
    public double getArticlePrice() {
        return this.articlePrice;
    }
    
    public void setArticlePrice(double articlePrice) {
        this.articlePrice = articlePrice;
    }
    public int getArticleStock() {
        return this.articleStock;
    }
    
    public void setArticleStock(int articleStock) {
        this.articleStock = articleStock;
    }
    public Set getWbCrStocks() {
        return this.wbCrStocks;
    }
    
    public void setWbCrStocks(Set wbCrStocks) {
        this.wbCrStocks = wbCrStocks;
    }
    public Set getWbCrBilldetails() {
        return this.wbCrBilldetails;
    }
    
    public void setWbCrBilldetails(Set wbCrBilldetails) {
        this.wbCrBilldetails = wbCrBilldetails;
    }




}


