package project.model;
// Generated Dec 12, 2018 11:08:37 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * WbCrStock generated by hbm2java
 */
public class WbCrStock  implements java.io.Serializable {


     private WbCrStockId id;
     private WbCrArticle wbCrArticle;
     private WbCrMovement wbCrMovement;
     private Integer strockNumber;
     private Date stockDate;
     private Integer stock;

    public WbCrStock() {
    }

	
    public WbCrStock(WbCrStockId id, WbCrArticle wbCrArticle, WbCrMovement wbCrMovement) {
        this.id = id;
        this.wbCrArticle = wbCrArticle;
        this.wbCrMovement = wbCrMovement;
    }
    public WbCrStock(WbCrStockId id, WbCrArticle wbCrArticle, WbCrMovement wbCrMovement, Integer strockNumber, Date stockDate, Integer stock) {
       this.id = id;
       this.wbCrArticle = wbCrArticle;
       this.wbCrMovement = wbCrMovement;
       this.strockNumber = strockNumber;
       this.stockDate = stockDate;
       this.stock = stock;
    }
   
    public WbCrStockId getId() {
        return this.id;
    }
    
    public void setId(WbCrStockId id) {
        this.id = id;
    }
    public WbCrArticle getWbCrArticle() {
        return this.wbCrArticle;
    }
    
    public void setWbCrArticle(WbCrArticle wbCrArticle) {
        this.wbCrArticle = wbCrArticle;
    }
    public WbCrMovement getWbCrMovement() {
        return this.wbCrMovement;
    }
    
    public void setWbCrMovement(WbCrMovement wbCrMovement) {
        this.wbCrMovement = wbCrMovement;
    }
    public Integer getStrockNumber() {
        return this.strockNumber;
    }
    
    public void setStrockNumber(Integer strockNumber) {
        this.strockNumber = strockNumber;
    }
    public Date getStockDate() {
        return this.stockDate;
    }
    
    public void setStockDate(Date stockDate) {
        this.stockDate = stockDate;
    }
    public Integer getStock() {
        return this.stock;
    }
    
    public void setStock(Integer stock) {
        this.stock = stock;
    }




}


