package project.model;
// Generated Dec 12, 2018 11:08:37 PM by Hibernate Tools 4.3.1



/**
 * WbCrStockId generated by hbm2java
 */
public class WbCrStockId  implements java.io.Serializable {


     private int articleId;
     private int movementId;

    public WbCrStockId() {
    }

    public WbCrStockId(int articleId, int movementId) {
       this.articleId = articleId;
       this.movementId = movementId;
    }
   
    public int getArticleId() {
        return this.articleId;
    }
    
    public void setArticleId(int articleId) {
        this.articleId = articleId;
    }
    public int getMovementId() {
        return this.movementId;
    }
    
    public void setMovementId(int movementId) {
        this.movementId = movementId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof WbCrStockId) ) return false;
		 WbCrStockId castOther = ( WbCrStockId ) other; 
         
		 return (this.getArticleId()==castOther.getArticleId())
 && (this.getMovementId()==castOther.getMovementId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getArticleId();
         result = 37 * result + this.getMovementId();
         return result;
   }   


}


