package project.model;
// Generated Dec 12, 2018 11:08:37 PM by Hibernate Tools 4.3.1



/**
 * WbCrBilldetailId generated by hbm2java
 */
public class WbCrBilldetailId  implements java.io.Serializable {


     private int cityId;
     private int clientId;
     private int billId;
     private int articleId;

    public WbCrBilldetailId() {
    }

    public WbCrBilldetailId(int cityId, int clientId, int billId, int articleId) {
       this.cityId = cityId;
       this.clientId = clientId;
       this.billId = billId;
       this.articleId = articleId;
    }
   
    public int getCityId() {
        return this.cityId;
    }
    
    public void setCityId(int cityId) {
        this.cityId = cityId;
    }
    public int getClientId() {
        return this.clientId;
    }
    
    public void setClientId(int clientId) {
        this.clientId = clientId;
    }
    public int getBillId() {
        return this.billId;
    }
    
    public void setBillId(int billId) {
        this.billId = billId;
    }
    public int getArticleId() {
        return this.articleId;
    }
    
    public void setArticleId(int articleId) {
        this.articleId = articleId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof WbCrBilldetailId) ) return false;
		 WbCrBilldetailId castOther = ( WbCrBilldetailId ) other; 
         
		 return (this.getCityId()==castOther.getCityId())
 && (this.getClientId()==castOther.getClientId())
 && (this.getBillId()==castOther.getBillId())
 && (this.getArticleId()==castOther.getArticleId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCityId();
         result = 37 * result + this.getClientId();
         result = 37 * result + this.getBillId();
         result = 37 * result + this.getArticleId();
         return result;
   }   


}


