package project.model;
// Generated Dec 12, 2018 11:08:37 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * WbCrMovement generated by hbm2java
 */
public class WbCrMovement  implements java.io.Serializable {


     private int movementId;
     private String movementName;
     private String movementDirection;
     private Set wbCrStocks = new HashSet(0);

    public WbCrMovement() {
    }

	
    public WbCrMovement(int movementId, String movementName, String movementDirection) {
        this.movementId = movementId;
        this.movementName = movementName;
        this.movementDirection = movementDirection;
    }
    public WbCrMovement(int movementId, String movementName, String movementDirection, Set wbCrStocks) {
       this.movementId = movementId;
       this.movementName = movementName;
       this.movementDirection = movementDirection;
       this.wbCrStocks = wbCrStocks;
    }
   
    public int getMovementId() {
        return this.movementId;
    }
    
    public void setMovementId(int movementId) {
        this.movementId = movementId;
    }
    public String getMovementName() {
        return this.movementName;
    }
    
    public void setMovementName(String movementName) {
        this.movementName = movementName;
    }
    public String getMovementDirection() {
        return this.movementDirection;
    }
    
    public void setMovementDirection(String movementDirection) {
        this.movementDirection = movementDirection;
    }
    public Set getWbCrStocks() {
        return this.wbCrStocks;
    }
    
    public void setWbCrStocks(Set wbCrStocks) {
        this.wbCrStocks = wbCrStocks;
    }




}


