package project.model;
// Generated Dec 12, 2018 11:08:37 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * WbCrBill generated by hbm2java
 */
public class WbCrBill  implements java.io.Serializable {


     private WbCrBillId id;
     private WbCrCity wbCrCity;
     private WbCrClient wbCrClient;
     private Date billDate;
     private Set wbCrBilldetails = new HashSet(0);

    public WbCrBill() {
    }

	
    public WbCrBill(WbCrBillId id, WbCrCity wbCrCity, WbCrClient wbCrClient, Date billDate) {
        this.id = id;
        this.wbCrCity = wbCrCity;
        this.wbCrClient = wbCrClient;
        this.billDate = billDate;
    }
    public WbCrBill(WbCrBillId id, WbCrCity wbCrCity, WbCrClient wbCrClient, Date billDate, Set wbCrBilldetails) {
       this.id = id;
       this.wbCrCity = wbCrCity;
       this.wbCrClient = wbCrClient;
       this.billDate = billDate;
       this.wbCrBilldetails = wbCrBilldetails;
    }
   
    public WbCrBillId getId() {
        return this.id;
    }
    
    public void setId(WbCrBillId id) {
        this.id = id;
    }
    public WbCrCity getWbCrCity() {
        return this.wbCrCity;
    }
    
    public void setWbCrCity(WbCrCity wbCrCity) {
        this.wbCrCity = wbCrCity;
    }
    public WbCrClient getWbCrClient() {
        return this.wbCrClient;
    }
    
    public void setWbCrClient(WbCrClient wbCrClient) {
        this.wbCrClient = wbCrClient;
    }
    public Date getBillDate() {
        return this.billDate;
    }
    
    public void setBillDate(Date billDate) {
        this.billDate = billDate;
    }
    public Set getWbCrBilldetails() {
        return this.wbCrBilldetails;
    }
    
    public void setWbCrBilldetails(Set wbCrBilldetails) {
        this.wbCrBilldetails = wbCrBilldetails;
    }




}


