package project.model;
// Generated Dec 12, 2018 11:08:37 PM by Hibernate Tools 4.3.1



/**
 * WbCrBilldetail generated by hbm2java
 */
public class WbCrBilldetail  implements java.io.Serializable {


     private WbCrBilldetailId id;
     private WbCrArticle wbCrArticle;
     private WbCrBill wbCrBill;
     private int detailAmount;

    public WbCrBilldetail() {
    }

    public WbCrBilldetail(WbCrBilldetailId id, WbCrArticle wbCrArticle, WbCrBill wbCrBill, int detailAmount) {
       this.id = id;
       this.wbCrArticle = wbCrArticle;
       this.wbCrBill = wbCrBill;
       this.detailAmount = detailAmount;
    }
   
    public WbCrBilldetailId getId() {
        return this.id;
    }
    
    public void setId(WbCrBilldetailId id) {
        this.id = id;
    }
    public WbCrArticle getWbCrArticle() {
        return this.wbCrArticle;
    }
    
    public void setWbCrArticle(WbCrArticle wbCrArticle) {
        this.wbCrArticle = wbCrArticle;
    }
    public WbCrBill getWbCrBill() {
        return this.wbCrBill;
    }
    
    public void setWbCrBill(WbCrBill wbCrBill) {
        this.wbCrBill = wbCrBill;
    }
    public int getDetailAmount() {
        return this.detailAmount;
    }
    
    public void setDetailAmount(int detailAmount) {
        this.detailAmount = detailAmount;
    }




}


