package project.model;
// Generated Dec 12, 2018 11:08:37 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * WbCrClient generated by hbm2java
 */
public class WbCrClient  implements java.io.Serializable {


     private int clientId;
     private String clientDni;
     private String clientName;
     private String clientAddress;
     private Set wbCrBills = new HashSet(0);

    public WbCrClient() {
    }

	
    public WbCrClient(int clientId, String clientDni, String clientName) {
        this.clientId = clientId;
        this.clientDni = clientDni;
        this.clientName = clientName;
    }
    public WbCrClient(int clientId, String clientDni, String clientName, String clientAddress, Set wbCrBills) {
       this.clientId = clientId;
       this.clientDni = clientDni;
       this.clientName = clientName;
       this.clientAddress = clientAddress;
       this.wbCrBills = wbCrBills;
    }
   
    public int getClientId() {
        return this.clientId;
    }
    
    public void setClientId(int clientId) {
        this.clientId = clientId;
    }
    public String getClientDni() {
        return this.clientDni;
    }
    
    public void setClientDni(String clientDni) {
        this.clientDni = clientDni;
    }
    public String getClientName() {
        return this.clientName;
    }
    
    public void setClientName(String clientName) {
        this.clientName = clientName;
    }
    public String getClientAddress() {
        return this.clientAddress;
    }
    
    public void setClientAddress(String clientAddress) {
        this.clientAddress = clientAddress;
    }
    public Set getWbCrBills() {
        return this.wbCrBills;
    }
    
    public void setWbCrBills(Set wbCrBills) {
        this.wbCrBills = wbCrBills;
    }




}


