package project.model;
// Generated Dec 12, 2018 11:08:37 PM by Hibernate Tools 4.3.1

import java.util.Objects;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;




/**
 * WbCrUser generated by hbm2java
 */

@ManagedBean()
@SessionScoped
public class WbCrUser  implements java.io.Serializable {


     private int userId;
     private String userName;
     private String userPassword;
     private String userPermission;

    public WbCrUser() {
    }

    public WbCrUser(int userId, String userName, String userPassword, String userPermission) {
       this.userId = userId;
       this.userName = userName;
       this.userPassword = userPassword;
       this.userPermission = userPermission;
    }
   
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getUserPassword() {
        return this.userPassword;
    }
    
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }
    public String getUserPermission() {
        return this.userPermission;
    }
    
    public void setUserPermission(String userPermission) {
        this.userPermission = userPermission;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 31 * hash + Objects.hashCode(this.userName);
        hash = 31 * hash + Objects.hashCode(this.userPassword);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final WbCrUser other = (WbCrUser) obj;
        if (!Objects.equals(this.userName, other.userName)) {
            return false;
        }
        return Objects.equals(this.userPassword, other.userPassword);
    }

    
    
}


